# Generated by Django 5.2.11 on 2026-02-14 07:16

import django.core.validators
import django.db.models.deletion
import taggit.managers
import apps.common.uuid_utils
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_max_retail_price_alter_product_price_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=apps.common.uuid_utils.generate_uuid7, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('bio', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.product')),
                ('isbn_10', models.CharField(blank=True, default='', max_length=15)),
                ('isbn_13', models.CharField(blank=True, default='', max_length=15)),
                ('book_language', models.CharField(blank=True, default='', max_length=255)),
                ('book_edition', models.CharField(blank=True, default='', max_length=255)),
                ('cover_type', models.CharField(blank=True, default='', max_length=255)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('published_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-updated_on',),
            },
            bases=('inventory.product',),
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=apps.common.uuid_utils.generate_uuid7, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Soap',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.product')),
                ('brand', models.CharField(blank=True, default='', max_length=255)),
                ('fragrance', models.CharField(blank=True, default='', max_length=255)),
                ('net_weight_grams', models.PositiveIntegerField(default=0)),
                ('skin_type', models.CharField(blank=True, default='', max_length=100)),
                ('shelf_life_months', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-updated_on',),
            },
            bases=('inventory.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='date_sale_price_ends',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date_sale_price_starts',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gcid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='part_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='product_dimension_breadth',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='product_dimension_height',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='product_dimension_length',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='product_dimension_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='quality',
            field=models.CharField(choices=[('NEW', 'New'), ('USED_LOOKS_GOOD', 'Used - Looks Good'), ('USED_ACCEPTABLE', 'Used - Acceptable')], default='USED_LOOKS_GOOD', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='quality_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='sell_option',
            field=models.CharField(choices=[('SELF_SELL', 'Self Sell'), ('SMART_SELL', 'Smart Sell')], default='SMART_SELL', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_state',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='product',
            name='upc',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='view_counter',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('product_dimension_length__gte', 0)), name='product_dimension_length_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('product_dimension_breadth__gte', 0)), name='product_dimension_breadth_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('product_dimension_height__gte', 0)), name='product_dimension_height_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('product_dimension_weight__gte', 0)), name='product_dimension_weight_non_negative'),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='books', to='inventory.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='inventory.publisher'),
        ),
    ]
