# Generated by Django 5.2.11 on 2026-02-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_author_book_publisher_soap_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('name',), 'verbose_name_plural': 'authors'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ('name',), 'verbose_name_plural': 'publishers'},
        ),
        migrations.AddField(
            model_name='author',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='publisher',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publisher',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
