# Generated by Django 5.2.11 on 2026-02-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_author_options_alter_publisher_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quality',
            field=models.CharField(choices=[('NEW', 'New'), ('USED_LOOKS_NEW', 'Used - Looks Like New'), ('USED_LOOKS_GOOD', 'Used - Looks Good'), ('USED_ACCEPTABLE', 'Used - Acceptable')], default='USED_LOOKS_GOOD', max_length=200),
        ),
    ]
