# Generated by Django 5.2.11 on 2026-02-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_category_options_product_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='goodread_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
