# Generated by Django 5.2.11 on 2026-02-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_goodread_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='goodread_id',
        ),
        migrations.AddField(
            model_name='book',
            name='goodread_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
