# Generated by Django 5.2.11 on 2026-02-18 07:14

import apps.common.uuid_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_product_goodread_id_book_goodread_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.UUIDField(db_index=True, default=apps.common.uuid_utils.generate_uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(db_index=True, default=apps.common.uuid_utils.generate_uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(db_index=True, default=apps.common.uuid_utils.generate_uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='uuid',
            field=models.UUIDField(db_index=True, default=apps.common.uuid_utils.generate_uuid7, editable=False, unique=True),
        ),
    ]
