# Generated by Django 5.2.11 on 2026-02-21 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_alter_author_uuid_alter_category_uuid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="min_retail_price",
        ),
    ]
