# Generated by Django 5.2.11 on 2026-02-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_rename_product_price_to_min_retail_price"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="product",
            name="product_price_non_negative",
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(min_retail_price__gte=0),
                name="product_price_non_negative",
            ),
        ),
    ]
