# Generated by Django 5.2.11 on 2026-02-21 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_product_product_price_non_negative_and_more'),
        ('photos', '0002_alter_photo_uuid_alter_photoattachment_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_profile', to='photos.photo'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='brand_image',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_brand', to='photos.photo'),
        ),
    ]
