# Generated by Django 5.2.11 on 2026-03-01 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_author_photo_publisher_brand_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantFeedSyncLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trigger_source', models.CharField(choices=[('MANUAL', 'Manual'), ('PRODUCT_UPDATE', 'Product Update'), ('SCHEDULED_12H', 'Scheduled 12h'), ('SCHEDULED_24H', 'Scheduled 24h')], default='MANUAL', max_length=32)),
                ('run_mode', models.CharField(choices=[('FULL', 'Full'), ('DELTA', 'Delta')], default='FULL', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=12)),
                ('started_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('completed_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('feed_relative_path', models.CharField(blank=True, default='', max_length=512)),
                ('feed_public_url', models.URLField(blank=True, default='', max_length=1000)),
                ('feed_checksum', models.CharField(blank=True, default='', max_length=128)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('success_items', models.PositiveIntegerField(default=0)),
                ('failed_items', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_feed_sync_logs', to='inventory.product')),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
    ]
