# Generated by Django 5.2.11 on 2026-03-01 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_merchantfeedsynclog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantFeedDebounceEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dedupe_key', models.CharField(max_length=255, unique=True)),
                ('next_sync_on', models.DateTimeField(db_index=True)),
                ('last_seen_on', models.DateTimeField(auto_now=True)),
                ('enqueue_count', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_feed_debounce_entries', to='inventory.product')),
            ],
            options={
                'ordering': ('next_sync_on', 'id'),
            },
        ),
    ]
