# Generated by Django 5.2.11 on 2026-05-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_merchantfeeddebounceentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quality',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
