# Generated by Django 5.2.11 on 2026-05-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_book_metadata_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISBNLookupLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(db_index=True, max_length=13)),
                ('source', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('hit', 'Hit'), ('miss', 'Miss'), ('error', 'Error'), ('rate_limited', 'Rate Limited')], max_length=20)),
                ('latency_ms', models.IntegerField()),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
    ]
