# Generated by Django 5.2.11 on 2026-05-26 19:44 — hand-edited for the M2M→through swap.
#
# Django refuses to AlterField an M2M to add/remove `through=`:
#     ValueError: Cannot alter field ... they are not compatible types
#     (you cannot alter to or from M2M fields, or add or remove through= on M2M fields)
#
# Workaround pattern:
#   1. CreateModel BookAuthor → creates `inventory_bookauthor` table.
#   2. RunPython copies (book_id, author_id) rows from the auto-created M2M
#      `inventory_book_authors` table into BookAuthor with role='author' and
#      order=0..N per book.
#   3. SeparateDatabaseAndState performs the AlterField in Django's *state*
#      (so the ORM knows about through=BookAuthor) while raw SQL drops the
#      now-redundant auto-created table.
#   4. Index + UniqueConstraint on BookAuthor are added afterwards.

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def copy_book_authors_forward(apps, schema_editor):
    """Copy existing Book↔Author pairs from the auto-created M2M table into BookAuthor.

    The old `inventory_book_authors` table only has (id, book_id, author_id) —
    no order/role columns. We assign role='author' and order=0..N per book,
    sequenced by the original join row's id (closest available proxy for
    insertion order, since first-listed author gets primary credit).
    """
    BookAuthor = apps.get_model("inventory", "BookAuthor")
    now = django.utils.timezone.now()
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT book_id, author_id FROM inventory_book_authors ORDER BY id")
        rows = cursor.fetchall()

    seen_per_book: dict[int, int] = {}
    to_create = []
    for book_id, author_id in rows:
        order = seen_per_book.get(book_id, 0)
        seen_per_book[book_id] = order + 1
        to_create.append(
            BookAuthor(
                book_id=book_id,
                author_id=author_id,
                order=order,
                role="author",
                created_on=now,  # bulk_create skips auto_now_add; set explicitly
            )
        )
    BookAuthor.objects.bulk_create(to_create, batch_size=200)


def copy_book_authors_reverse(apps, schema_editor):
    """If reversed, clear BookAuthor; the auto-M2M table will be restored by SeparateDatabaseAndState's reverse."""
    BookAuthor = apps.get_model("inventory", "BookAuthor")
    BookAuthor.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_isbnlookuplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISBNNotFoundCache',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('isbn_13', models.CharField(max_length=13, unique=True)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
                ('retry_after', models.DateTimeField(db_index=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-last_attempt_at',),
            },
        ),
        migrations.AddField(
            model_name='book',
            name='list_price_inr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='list_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('role', models.CharField(choices=[('author', 'Author'), ('editor', 'Editor'), ('translator', 'Translator'), ('illustrator', 'Illustrator')], default='author', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_books', to='inventory.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='inventory.book')),
            ],
            options={
                'ordering': ('book_id', 'order', 'id'),
            },
        ),
        # Copy data while the OLD auto-M2M table still exists.
        migrations.RunPython(copy_book_authors_forward, copy_book_authors_reverse),
        # Swap Book.authors to through=BookAuthor in Django's model state, and
        # drop the old auto-created table at the DB level. Split is required
        # because Django's standard AlterField refuses to handle through= changes.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='book',
                    name='authors',
                    field=models.ManyToManyField(
                        blank=True,
                        related_name='books',
                        through='inventory.BookAuthor',
                        to='inventory.author',
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE inventory_book_authors;",
                    # Reverse is one-way here: data is already in BookAuthor.
                    # If you reverse this migration the reverse RunPython will
                    # clear BookAuthor anyway, so a no-op DROP-reverse is fine.
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='bookauthor',
            index=models.Index(fields=['book', 'order'], name='inventory_b_book_id_efabe5_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookauthor',
            constraint=models.UniqueConstraint(fields=('book', 'author', 'role'), name='bookauthor_unique_book_author_role'),
        ),
    ]
