# Generated by Django 5.2.11 on 2026-02-18 05:01

import django.db.models.deletion
import apps.common.uuid_utils
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0008_remove_product_goodread_id_book_goodread_id'),
        ('users', '0004_user_favourite_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=apps.common.uuid_utils.generate_uuid7, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('office_name', models.CharField(blank=True, default='', max_length=200)),
                ('pincode', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('office_type', models.CharField(blank=True, default='', max_length=200)),
                ('delivery_status', models.CharField(blank=True, default='', max_length=200)),
                ('division_name', models.CharField(blank=True, default='', max_length=200)),
                ('region_name', models.CharField(blank=True, default='', max_length=200)),
                ('circle_name', models.CharField(blank=True, default='', max_length=200)),
                ('taluk', models.CharField(blank=True, default='', max_length=200)),
                ('district_name', models.CharField(blank=True, default='', max_length=200)),
                ('state_name', models.CharField(blank=True, default='', max_length=200)),
                ('state_short_name', models.CharField(blank=True, default='', max_length=200)),
                ('telephone', models.CharField(blank=True, default='', max_length=20)),
                ('alternate_telephone', models.CharField(blank=True, default='', max_length=20)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=20)),
                ('head_post_master', models.CharField(blank=True, default='', max_length=255)),
                ('head_post_master_mobile_number', models.CharField(blank=True, default='', max_length=255)),
                ('related_suboffice', models.CharField(blank=True, default='', max_length=200)),
                ('related_headoffice', models.CharField(blank=True, default='', max_length=200)),
                ('post_office_address', models.TextField(blank=True, default='')),
                ('plus_code', models.CharField(blank=True, default='', max_length=255)),
                ('po_latitude', models.DecimalField(decimal_places=7, default=Decimal('0E-7'), max_digits=10)),
                ('po_longitude', models.DecimalField(decimal_places=7, default=Decimal('0E-7'), max_digits=10)),
                ('longitude', models.CharField(blank=True, default='', max_length=50)),
                ('latitude', models.CharField(blank=True, default='', max_length=50)),
                ('embargo', models.BooleanField(default=False)),
                ('remark', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'pincodes',
                'ordering': ('-updated_on', 'office_name', 'pincode'),
            },
        ),
        migrations.CreateModel(
            name='PackageProfile',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=apps.common.uuid_utils.generate_uuid7, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('package_profile_category', models.CharField(default='', max_length=255)),
                ('hsn_code', models.CharField(default='', max_length=255)),
                ('package_profile_description', models.CharField(default='', max_length=255)),
                ('weight_per_package', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('package_dimension_length', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('package_dimension_breadth', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('package_dimension_height', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_profiles', to='inventory.product')),
            ],
            options={
                'ordering': ('-updated_on',),
            },
        ),
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=apps.common.uuid_utils.generate_uuid7, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shipper_pkreqid', models.CharField(blank=True, default='', max_length=255)),
                ('pickup_scheduled_date', models.DateField()),
                ('pickup_ready_start_time', models.DateTimeField(blank=True, null=True)),
                ('pickup_ready_end_time', models.DateTimeField(blank=True, null=True)),
                ('no_of_packages', models.IntegerField(default=0)),
                ('total_weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('total_invoice_value', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('fright_charges', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('pickup_status', models.CharField(blank=True, choices=[('DRAFT', 'Save Pickup Request as DRAFT.'), ('BOOKED', 'Finalize Pickup Request as BOOKED.'), ('REQUEST_CANCEL', 'Request Admin for cancellation of this Pickup Request.'), ('READY_FOR_PICKUP', 'Pickup Request is packed and ready for pickup.'), ('CANCELLED', 'CANCEL this Pickup Request.'), ('PICKED_UP_AND_IN_TRANSIT', 'Pickup Request is picked up and in transit.'), ('PICKUP_REJECTED', 'Pickup Request is rejected for some reason by Logistics Team.'), ('RECEIVED', 'Pickup Request received at the Warehouse.'), ('RETURNED', 'Pickup Request Returned to source location.')], default='', max_length=255, null=True)),
                ('pickup_mode', models.CharField(choices=[('AIRWAYS_PRIORITY', 'Airways Priority Mode'), ('ROADWAYS_ECONOMY', 'Roadways Economy Mode')], default='ROADWAYS_ECONOMY', max_length=50)),
                ('pickup_instruction', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('reason_for_cancellation', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('from_address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pickup_from_address', to='users.address')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pickup_from_user', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ownerpickups', to=settings.AUTH_USER_MODEL)),
                ('to_address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pickup_to_address', to='users.address')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pickup_to_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_on',),
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=apps.common.uuid_utils.generate_uuid7, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('awb_number', models.CharField(default='', max_length=255)),
                ('weight_per_package', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('package_dimension_length', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('package_dimension_breadth', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('package_dimension_height', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('package_category', models.CharField(default='', max_length=255)),
                ('hsn_code', models.CharField(default='', max_length=255)),
                ('package_name', models.CharField(default='', max_length=255)),
                ('package_description', models.CharField(default='', max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='packs', to=settings.AUTH_USER_MODEL)),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='logistics.pickuprequest')),
            ],
            options={
                'ordering': ('-updated_on',),
            },
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=apps.common.uuid_utils.generate_uuid7, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shipper_shortname', models.CharField(default='', max_length=255)),
                ('shipper_name', models.CharField(default='', max_length=255)),
                ('shipper_account_number', models.CharField(default='', max_length=255)),
                ('shipper_account_name', models.CharField(default='', max_length=255)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipperowner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_on',),
            },
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='shipper',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipperpickups', to='logistics.shipper'),
        ),
    ]
