# Generated by Django 5.2.11 on 2026-02-20 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_package_uuid_alter_packageprofile_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='pickup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='logistics.pickuprequest'),
        ),
    ]
