# Generated by Django 4.2.20 on 2025-12-07 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, db_index=True, default='generic', help_text="String key for this event (e.g. 'welcome', 'order_shipped').", max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('target_url', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('send_email', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_subject', models.CharField(blank=True, max_length=255)),
                ('email_body', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Dynamic data for template rendering (e.g., order_id, first_name).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_caused', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('per_type', models.JSONField(blank=True, default=dict, help_text='Override channel selection per type (optional).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, help_text="Matches Notification.type (e.g. 'welcome', 'order_shipped').", max_length=64)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=32)),
                ('subject', models.CharField(blank=True, help_text='Email only: SMS/WhatsApp do not use subject.', max_length=255)),
                ('body', models.TextField(help_text='Django template markup allowed (HTML/Text). Use context variables.')),
                ('is_active', models.BooleanField(default=True, help_text='Disable a template without deleting it.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['type', 'channel'],
                'unique_together': {('type', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=32)),
                ('target', models.CharField(help_text='Where the message will be delivered (email / phone / WhatsApp ID).', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('gave_up', 'Gave Up')], db_index=True, default='pending', max_length=32)),
                ('attempt_count', models.PositiveIntegerField(default=0, help_text='How many times this delivery has been attempted.')),
                ('last_error', models.TextField(blank=True, help_text='The most recent failure message from provider/API.')),
                ('provider_message_id', models.CharField(blank=True, help_text='API-tracking ID (e.g., Twilio SID, Email Message ID).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'indexes': [models.Index(fields=['channel', 'status'], name='notificatio_channel_edd073_idx'), models.Index(fields=['created_at'], name='notificatio_created_f0c306_idx')],
            },
        ),
    ]
