# Generated by Django 5.2.11 on 2026-05-26 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppressedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('reason', models.CharField(choices=[('hard_bounce', 'Hard bounce'), ('complaint', 'Spam complaint'), ('manual', 'Manual')], max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reason'], name='notificatio_reason_99932a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SesEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('bounce', 'Bounce'), ('complaint', 'Complaint'), ('delivery', 'Delivery'), ('reject', 'Reject'), ('send', 'Send'), ('other', 'Other')], db_index=True, max_length=32)),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('recipient', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('subtype', models.CharField(blank=True, max_length=64)),
                ('diagnostic', models.TextField(blank=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ses_events', to='notifications.notificationdelivery')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['event_type', 'received_at'], name='notificatio_event_t_ef0448_idx'), models.Index(fields=['recipient', 'event_type'], name='notificatio_recipie_afe26f_idx')],
            },
        ),
    ]
