# Generated by Django 5.2.11 on 2026-02-24 00:00

import apps.common.uuid_utils
from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0012_author_photo_publisher_brand_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("uuid", models.UUIDField(db_index=True, default=apps.common.uuid_utils.generate_uuid7, editable=False, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("guest_token", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_on",),
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("uuid", models.UUIDField(db_index=True, default=apps.common.uuid_utils.generate_uuid7, editable=False, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("quantity", models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])),
                (
                    "cart",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="cart.cart"),
                ),
                (
                    "product",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cart_items", to="inventory.product"),
                ),
            ],
            options={
                "ordering": ("-created_on",),
            },
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_archived", False)),
                fields=("user",),
                name="cart_unique_active_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_archived", False)),
                fields=("guest_token",),
                name="cart_unique_active_guest",
            ),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.CheckConstraint(
                condition=models.Q(("user__isnull", False)) | models.Q(("guest_token__isnull", False)),
                name="cart_user_or_guest_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_archived", False)),
                fields=("cart", "product"),
                name="cartitem_unique_active_product",
            ),
        ),
    ]
