# Generated by Django 5.2.11 on 2026-02-09 01:10

import apps.users.managers
import django.db.models.deletion
import apps.common.uuid_utils
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def _legacy_email_verification_expiry():
    return timezone.now() + timezone.timedelta(hours=2)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(db_index=True, default=apps.common.uuid_utils.generate_uuid7, editable=False, unique=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('email_verification_token', models.UUIDField(default=apps.common.uuid_utils.generate_uuid7, editable=False, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verification_expiry', models.DateTimeField(default=_legacy_email_verification_expiry)),
                ('email_verified_on', models.DateTimeField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, default='', max_length=20)),
                ('mobile_verified_on', models.DateTimeField(blank=True, null=True)),
                ('upi_id', models.CharField(blank=True, default='', max_length=255)),
                ('upi_last_verified_on', models.DateTimeField(blank=True, null=True)),
                ('plan', models.CharField(choices=[('SELF_SELL', 'Self Sell'), ('SMART_SELL', 'Smart Sell'), ('DONATE_100', 'Donate 100%'), ('DONATE_50', 'Donate 50%')], default='SMART_SELL', max_length=20)),
                ('donate_books_option', models.CharField(default='0', max_length=20)),
                ('store_credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('SELLER', 'Seller'), ('CUSTOMER', 'Customer'), ('GUEST', 'Guest')], default='GUEST', max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('-updated_on',),
            },
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=apps.common.uuid_utils.generate_uuid7, editable=False, unique=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('mobile_num', models.CharField(blank=True, default='', max_length=20)),
                ('pincode', models.CharField(default='000000', max_length=10)),
                ('building_name', models.CharField(blank=True, default='', max_length=200)),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('area_sector', models.CharField(blank=True, default='', max_length=200)),
                ('landmark', models.CharField(blank=True, default='', max_length=200)),
                ('town_city', models.CharField(blank=True, default='', max_length=200)),
                ('state_region', models.CharField(blank=True, default='', max_length=200)),
                ('address_type', models.CharField(choices=[('RESIDENCE', 'Residence'), ('OFFICE', 'Office')], default='RESIDENCE', max_length=20)),
                ('default_shipping_address', models.BooleanField(default=False)),
                ('default_billing_address', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_on',),
            },
        ),
    ]
