# Generated by Django 5.2.11 on 2026-02-13 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_status_address_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified_on',
        ),
    ]
