# Generated by Django 5.2.11 on 2026-02-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_book',
            field=models.TextField(blank=True, default=''),
        ),
    ]
