# Generated by Django 5.2.11 on 2026-02-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_address_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
