# Generated by Django 5.2.11 on 2026-02-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_address_address_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="plan_locked",
            field=models.BooleanField(default=False),
        ),
    ]
