# Generated by Django 5.2.11 on 2026-02-21 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_uuid_alter_photoattachment_uuid'),
        ('users', '0007_user_plan_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='photos.photo'),
        ),
    ]
