# Generated by Django 5.2.11 on 2026-05-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_upi_verified_and_seller_plan_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='locality',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
