# Generated by Django 5.2.11 on 2026-05-25 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_address_locality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verification_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verification_token',
        ),
    ]
