# Generated by Django 5.2.11 on 2026-02-14 19:35

import django.db.models.deletion
import apps.common.uuid_utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=apps.common.uuid_utils.generate_uuid7, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, default='', max_length=200)),
                ('alt_tag', models.CharField(blank=True, default='', max_length=200)),
                ('image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('s3_key', models.CharField(max_length=1024, unique=True)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('upload_status', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADED', 'Uploaded')], default='PENDING', max_length=16)),
                ('uploaded_on', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.CreateModel(
            name='PhotoAttachment',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=apps.common.uuid_utils.generate_uuid7, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveBigIntegerField(db_index=True)),
                ('relation_type', models.CharField(default='gallery', max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='photos.photo')),
            ],
            options={
                'ordering': ('sort_order', '-created_on'),
                'indexes': [models.Index(fields=['content_type', 'object_id', 'relation_type'], name='photos_phot_content_5f4aa1_idx'), models.Index(fields=['photo', 'relation_type'], name='photos_phot_photo_i_a2e8cc_idx')],
                'constraints': [models.UniqueConstraint(fields=('photo', 'content_type', 'object_id', 'relation_type'), name='photo_attachment_unique_photo_target_relation'), models.UniqueConstraint(condition=models.Q(('is_archived', False), ('is_primary', True)), fields=('content_type', 'object_id', 'relation_type'), name='photo_attachment_one_primary_per_target_relation')],
            },
        ),
    ]
