# Generated by Django 5.2.11 on 2026-02-18 07:14

import apps.common.uuid_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='uuid',
            field=models.UUIDField(db_index=True, default=apps.common.uuid_utils.generate_uuid7, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='photoattachment',
            name='uuid',
            field=models.UUIDField(db_index=True, default=apps.common.uuid_utils.generate_uuid7, editable=False, unique=True),
        ),
    ]
