# Generated by Django 5.2.11 on 2026-02-24 00:00

import apps.common.uuid_utils
from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import migrations, models
import django.db.models.deletion
from decimal import Decimal


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentGateway",
            fields=[
                ("uuid", models.UUIDField(db_index=True, default=apps.common.uuid_utils.generate_uuid7, editable=False, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("config", models.JSONField(blank=True, default=dict)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                ("uuid", models.UUIDField(db_index=True, default=apps.common.uuid_utils.generate_uuid7, editable=False, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("type", models.CharField(choices=[("PERCENT", "Percent"), ("FLAT", "Flat")], max_length=20)),
                ("value", models.DecimalField(decimal_places=2, max_digits=12, validators=[MinValueValidator(Decimal("0.00"))])),
                ("min_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("max_usage", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={"ordering": ("code",)},
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("uuid", models.UUIDField(db_index=True, default=apps.common.uuid_utils.generate_uuid7, editable=False, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("gateway_order_id", models.CharField(blank=True, default="", max_length=255)),
                ("gateway_payment_id", models.CharField(blank=True, default="", max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12, validators=[MinValueValidator(Decimal("0.00"))])),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("status", models.CharField(choices=[("INITIATED", "Initiated"), ("AUTHORIZED", "Authorized"), ("CAPTURED", "Captured"), ("FAILED", "Failed"), ("REFUNDED", "Refunded")], default="INITIATED", max_length=20)),
                ("response", models.JSONField(blank=True, default=dict)),
                (
                    "gateway",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="payments.paymentgateway"),
                ),
                (
                    "order",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="orders.order"),
                ),
            ],
            options={"ordering": ("-created_on",)},
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                ("uuid", models.UUIDField(db_index=True, default=apps.common.uuid_utils.generate_uuid7, editable=False, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12, validators=[MinValueValidator(Decimal("0.00"))])),
                ("gateway_refund_id", models.CharField(blank=True, default="", max_length=255)),
                ("status", models.CharField(choices=[("INITIATED", "Initiated"), ("PROCESSING", "Processing"), ("COMPLETED", "Completed"), ("FAILED", "Failed")], default="INITIATED", max_length=20)),
                (
                    "payment",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="refunds", to="payments.payment"),
                ),
            ],
            options={"ordering": ("-created_on",)},
        ),
        migrations.CreateModel(
            name="CouponUsage",
            fields=[
                ("uuid", models.UUIDField(db_index=True, default=apps.common.uuid_utils.generate_uuid7, editable=False, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("used_on", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="usages", to="payments.coupon"),
                ),
                (
                    "order",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="coupon_usages", to="orders.order"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="coupon_usages", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"ordering": ("-used_on",)},
        ),
    ]
